{% extends "core/template-base.phtml" %}

{% block title %}Report {{title}}{% endblock %}

{% block additional_headers %}
<link rel="stylesheet" type="text/css" href="{{portal_url}}vendor/jquery/jquery-ui.min.css"/>
<link rel="stylesheet" type="text/css" href="{{portal_url}}vendor/datatables/datatables.min.css"/>
<link rel="stylesheet" type="text/css" href="{{portal_url}}vendor/chosen/chosen.min.css"/>
<link rel="stylesheet" type="text/css" href="{{portal_url}}styles/{{portal_style}}/admin.css" />
<script type="text/javascript" src="{{portal_url}}vendor/jquery/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="{{portal_url}}vendor/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{portal_url}}vendor/datatables/datatables.min.js"></script>
<script type="text/javascript" src="{{portal_url}}vendor/moment/moment.js"></script>
<script type="text/javascript" src="{{portal_url}}vendor/datatables/datetime-moment.js"></script>
<script type="text/javascript" src="{{portal_url}}vendor/chosen/chosen.jquery.min.js"></script>
{% endblock %}

{% block content %}
<div class="block">
    <div class="blocktitle">
        Report {{title}}
    </div>
    <div class="blockbody">
        <form id="options" method="get">
            {% if accounts|length > 0 %}
                <label for="account">Account</label>
                <select id="account" name="account" data-placeholder="Choose an account" class="chosen-select">
                    <option value="null"></option>
                    {% for row in accounts %}
                        {% if row[0] == account %}
                            <option value="{{ row[0] }}" SELECTED>{{ row[1] }}</option>
                        {% else %}
                            <option value="{{ row[0] }}">{{ row[1] }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            {% endif %}
            {% if characters|length > 0 %}
                <label for="character">Character</label>
                <select id="character" name="character" data-placeholder="Choose a character" class="chosen-select">
                    <option value="null"></option>
                    {% for row in characters %}
                        {% if row[0] == character %}
                            <option value="{{ row[0] }}" SELECTED>{{ row[1] }}</option>
                        {% else %}
                            <option value="{{ row[0] }}">{{ row[1] }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            {% endif %}
        </form><hr />
        <table id="reports-list" class="display table">
            <thead>
                <tr>
                    {% for col in results[0]|keys %}
                        <th>{{col}}</th>
                    {% endfor %}
                </tr>
            </thead>
            {% for row in results %}
            <tr>
                {% for col in row %}
                    <td>{{col|raw}}</td>
                {% endfor %}
            </tr>
            {% endfor %}
            <tfoot>
                <tr>
                    {% for col in results[0]|keys %}
                        <th>{{col}}</th>
                    {% endfor %}
                </tr>
            </tfoot>
        </table>

        {% if results|length == 0 %}
            No data found.
        {% endif %}
    </div>
</div>

<script type="text/javascript">
$(".chosen-select").chosen({disable_search_threshold: 10, width: "220px"});
$("#account").chosen().change(function() {
    $("#character").val('null');
    $('#options').submit();
});
$("#character").chosen().change(function() {
    $('#options').submit();
});

$(document).ready(function() {
    var dt = $('#reports-list').DataTable({
    });
});
</script>
{% endblock %}