{% extends "core/template-base.phtml" %}

{% block title %}{{portal_name}} Account Portal{% endblock %}

{% block content %}
<div class="block">
    <div class="blocktitle">
        Welcome {{username}}
    </div>
    <div class="blockbody">
        If you would like to change your password, enter a new password below, then click "Change Password".
        <form method="post" action="changepassword">
            <table width="100%">
                <tr>
                    <td align="right"><label for="password">New Password</label></td>
                    <td><input type="password" name="password" maxlength=16></td>
                </tr><tr>
                <tr>
                    <td colspan="2" align="right">
                        <input type="submit" name="change" value="Change Password">
                    </td>
                </tr>
            </table>
            <input type="hidden" name="{{csrf.keys.name}}" value="{{csrf.name}}">
            <input type="hidden" name="{{csrf.keys.value}}" value="{{csrf.value}}">
        </form>
    </div>
</div>

<div class="block">
    <div class="blocktitle">
        Your Characters
    </div>
    <div class="blockbody">
        {{ include('core/block-character-list.phtml') }}
    </div>
</div>

{% if lockedcharacters|length > 0 %}
<div class="block">
    <div class="blocktitle">
        Characters Locked For Transfer
    </div>
    <div class="blockbody">
        <p>The following characters are currently locked for pending server transfer. If a transfer has somehow failed, you can unlock them below.</p>
        <ul>
        {% for character in lockedcharacters %}
            <li>{{character.Name}} - {{character.AccSvrLock}} <form method="Post" action="{{portal_url}}federation/clear-transfer" style="display: inline-block;"><input type="submit" value="Unlock"><input type="hidden" name="character" value="{{character.datauri}}"></form></li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endif %}

<div class="block">
    <div class="blocktitle">
        Character Transfer
    </div>
    <div class="blockbody">
        <form method="post" action="./federation/transfer-character-request">
            <p>Please select a server and character to transfer:</p>
            <label for="server">Server</label>
            <select name="server">
                {% for Server in federation %}
                    {% if Server.Policy.AllowOutgoing == true  %}
                        <option value="{{Server.Name}}">{{Server.Name}}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <br />
            <label for="character">Character</label>
            <select name="character">
            {% for Character in characters %}
                <option value="{{Character.datauri}}">{{Character.Name}}</option>
            {% endfor %}
            </select>
            <br />
            <input type="submit" name="select" value="Transfer Now"/>
            <input type="hidden" name="{{csrf.keys.name}}" value="{{csrf.name}}">
            <input type="hidden" name="{{csrf.keys.value}}" value="{{csrf.value}}">
        </form>
    </div>
</div>
{% endblock %}