{% extends "core/template-base.phtml" %}

{% block title %}Report {{title}}{% endblock %}

{% block additional_headers %}
<link rel="stylesheet" type="text/css" href="{{portal_url}}vendor/jquery/jquery-ui.min.css"/>
<link rel="stylesheet" type="text/css" href="{{portal_url}}vendor/datatables/datatables.min.css"/>
<link rel="stylesheet" type="text/css" href="{{portal_url}}styles/{{portal_style}}/admin.css" />
<script type="text/javascript" src="{{portal_url}}vendor/jquery/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="{{portal_url}}vendor/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{portal_url}}vendor/datatables/datatables.min.js"></script>
<script type="text/javascript" src="{{portal_url}}vendor/moment/moment.js"></script>
<script type="text/javascript" src="{{portal_url}}vendor/datatables/datetime-moment.js"></script>
{% endblock %}

{% block content %}
<div class="block">
    <div class="blocktitle">
        Report {{title}}
    </div>
    <div class="blockbody">
        <table id="reports-list" class="display table">
            <thead>
                <tr>
                    {% for col in results[0]|keys %}
                        <th>{{col}}</th>
                    {% endfor %}
                </tr>
            </thead>
            {% for row in results %}
            <tr>
                {% for col in row %}
                    <td>{{col}}</td>
                {% endfor %}
            </tr>
            {% endfor %}
            <tfoot>
                <tr>
                    {% for col in results[0]|keys %}
                        <th>{{col}}</th>
                    {% endfor %}
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    var dt = $('#reports-list').DataTable({
    });
});
</script>
{% endblock %}