<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{{portal_url}}favicon.ico"/>
    <title>{% block title %}{% endblock %}</title>
    <link href="{{portal_url}}styles\freedom\style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="logo"><img src="{{portal_url}}images\ouroborosLogo.png" width="409"></div>
<div id="content">

    <table>
        <tr>
            <td valign="top">
                <div class="nav">
                    {% macro menuMacro(menu, level) -%}

                      {# Set our default level as an integer. #}
                      {% set default_level = 1 %}

                      <ul class="menu-level--{{ level|default(default_level) }}">
                        {% for menu_item in menu %}
                          {# Check if this is the active item. #}
                          {% set active = (menu_item.active) ? ' is-active' : '' %}

                          {# Check if this item is in the active trail. #}
                          {% set active = active ~ ((menu_item.active_trail) ? ' is-active-trail' : '') %}

                          <li class="menu__item{{ active }}">
                            <a href="{{ menu_item.url }}"  class="menu__link{{ active }} navitem">{{ menu_item.text }}</a>
                            {% if menu_item.submenu %}
                                {# Since this menu item has a submenu, recall function and increment counter. #}
                              {{ _self.menuMacro(menu_item.submenu, level|default(default_level) + 1) }}
                            {% endif %}
                          </li>
                        {% endfor %}
                        {% include 'menuitems.phtml' ignore missing %}
                      </ul>
                    {%- endmacro %}

                    {% import _self as menu %}
                    {{ menu.menuMacro(menu_tree) }}
                </div>

                <br />
                <div class="littleblock">
                    <div class="blocktitle">
                        {% if portal_lfg_only == true %}
                            {{ online.List|length }} Players LFG
                        {% else %}
                            {{online.Count}} Players Online
                        {% endif %}
                    </div>
                    <div class="blockbody onlinelist">
                        {% if portal_lfg_only == true %}
                            <span>{{online.Count}} Players Online</span><br />
                        {% endif %}

                        <ul class='onlinelist'>
                        {% for map in online.MapList %}
                            <li><div>{{ map }}</div>
                            <ul>

                            {% for char in online.List %}
                                {% if char.MapName == map %}
                                    <li>{{ char.Name }}</li>
                                {% endif %}
                            {% endfor %}
                            </ul></li>
                        {% endfor %}
                        </ul>
                    </div>
                </div>

            </td>
            <td valign="top">
                {% block content %}{% endblock %}
            </td>
        </tr>
    </table>
</div>

</body>
</html>