<div class="block">
    <div class="blocktitle">
        Client Download
    </div>
    <div class="blockbody">
        <p>To download the client, please follow these steps:</p>
        <ol>
            <li>Download the client <a href="https://drive.google.com/open?id=1rHNhoAPn6haVt6afLTxoGvh5pAPjT_Vy">from here</a>.</li>
            <li>Extract it somewhere convenient.</li>
            <li>Run "AurorisCOH.bat" and login with the account you created.</li>
        </ol>
    </div>
</div>