<ul class="character">
{% for character in characters %}
    <li>

    {#### Alignment ####}

    {% set PlayerType, PlayerSubType, PlayerPraetorian = 0, 0, 0 %}

    {% if character.PlayerType is defined                        %}
    {%    set PlayerType = character.PlayerType                  %}
    {% endif                                                     %}

    {% if character.PlayerSubType is defined                     %}
    {%    set PlayerSubType = character.PlayerSubType            %}
    {% endif                                                     %}

    {% if character.PraetorianProgress is defined                %}
    {%    set PlayerPraetorian = character.PraetorianProgress    %}
    {% endif                                                     %}

    {% if PlayerPraetorian == 1                                  %}
        <img src="{{portal_url}}images/icons/alignment/neutral.png" alt="Neutral">
    {% elseif PlayerPraetorian == 2                              %}
        {% if PlayerType == 0  %}
            <img src="{{portal_url}}images/icons/alignment/resistance.png" alt="Praetorian Resistance">
        {% endif %}

        {% if PlayerType == 1 %}
            <img src="{{portal_url}}images/icons/alignment/loyalist.png" alt="Praetorian Loyalist">
        {% endif %}
    {% elseif PlayerPraetorian == 6                              %}
        <img src="{{portal_url}}images/icons/alignment/neutral.png" alt="Neutral">
    {% else                                                      %}
        {% if PlayerType == 0 and PlayerSubType == 0 %}
            <img src="{{portal_url}}images/icons/alignment/hero.png" alt="Hero">
        {% endif %}

        {% if PlayerType == 0 and PlayerSubType == 1 %}
            <img src="{{portal_url}}images/icons/alignment/hero.png" alt="Paragon">
        {% endif %}

        {% if PlayerType == 0 and PlayerSubType == 2 %}
            <img src="{{portal_url}}images/icons/alignment/vigilante.png" alt="Vigilante">
        {% endif %}

        {% if PlayerType == 1 and PlayerSubType == 0 %}
            <img src="{{portal_url}}images/icons/alignment/villain.png" alt="Villain">
        {% endif %}

        {% if PlayerType == 1 and PlayerSubType == 1 %}
            <img src="{{portal_url}}images/icons/alignment/villain.png" alt="Tyrant">
        {% endif %}

        {% if PlayerType == 1 and PlayerSubType == 2 %}
            <img src="{{portal_url}}images/icons/alignment/rogue.png" alt="Rogue">
        {% endif %}
    {% endif                                                     %}

    {#### Class #####}

    {% if character.Class == 1 %}<img src="{{portal_url}}images/icons/archetype/blaster.png" alt="Blaster">{% endif %}
    {% if character.Class == 2 %}<img src="{{portal_url}}images/icons/archetype/controler.png" alt="Controller">{% endif %}
    {% if character.Class == 3 %}<img src="{{portal_url}}images/icons/archetype/defender.png" alt="Defender">{% endif %}
    {% if character.Class == 4 %}<img src="{{portal_url}}images/icons/archetype/scrapper.png" alt="Scrapper">{% endif %}
    {% if character.Class == 5 %}<img src="{{portal_url}}images/icons/archetype/tanker.png" alt="Tanker">{% endif %}
    {% if character.Class == 9198 %}<img src="{{portal_url}}images/icons/archetype/mastermind.png" alt="Mastermind">{% endif %}
    {% if character.Class == 9200 %}<img src="{{portal_url}}images/icons/archetype/stalker.png" alt="Stalker">{% endif %}
    {% if character.Class == 9201 %}<img src="{{portal_url}}images/icons/archetype/brute.png" alt="Brute">{% endif %}
    {% if character.Class == 9700 %}<img src="{{portal_url}}images/icons/archetype/dominator.png" alt="Dominator">{% endif %}
    {% if character.Class == 10929 %}<img src="{{portal_url}}images/icons/archetype/corruptor.png" alt="Corruptor">{% endif %}
    {% if character.Class == 7076 %}<img src="{{portal_url}}images/icons/archetype/warshade.png" alt="Warshade">{% endif %}
    {% if character.Class == 7018 %}<img src="{{portal_url}}images/icons/archetype/peacebringer.png" alt="Peacebringer">{% endif %}
    {% if character.Class == 37071 %}<img src="{{portal_url}}images/icons/archetype/arachnos_soldier.png" alt="Arachnos Soldier">{% endif %}
    {% if character.Class == 37072 %}<img src="{{portal_url}}images/icons/archetype/arachnos_widow.png" alt="Arachnos Widow">{% endif %}

    {#### Origin #####}

    {% if character.Origin == 6 %}<img src="{{portal_url}}images/icons/origin/science.png" alt="Science">{% endif %}
    {% if character.Origin == 7 %}<img src="{{portal_url}}images/icons/origin/mutation.png" alt="Mutation">{% endif %}
    {% if character.Origin == 8 %}<img src="{{portal_url}}images/icons/origin/magic.png" alt="Magic">{% endif %}
    {% if character.Origin == 9 %}<img src="{{portal_url}}images/icons/origin/technology.png" alt="Technology">{% endif %}
    {% if character.Origin == 10 %}<img src="{{portal_url}}images/icons/origin/natural.png" alt="Natural">{% endif %}

    <a href="./api/character/raw?q={{character.datauri}}">{{character.Name}}</a>

    {#### Maps ####}

    {% if character.StaticMapId == 1 %}Atlas Park{% endif %}
    {% if character.StaticMapId == 3 %}Cimerora{% endif %}
    {% if character.StaticMapId == 4 %}Midnighter Club{% endif %}
    {% if character.StaticMapId == 5 %}Kings Row{% endif %}
    {% if character.StaticMapId == 6 %}Steel Canyon{% endif %}
    {% if character.StaticMapId == 7 %}Skyway City{% endif %}
    {% if character.StaticMapId == 8 %}Talos Island{% endif %}
    {% if character.StaticMapId == 9 %}Independence Port{% endif %}
    {% if character.StaticMapId == 10 %}Founders' Falls{% endif %}
    {% if character.StaticMapId == 11 %}Brickstown{% endif %}
    {% if character.StaticMapId == 12 %}Perez Park{% endif %}
    {% if character.StaticMapId == 13 %}'Boomtown'{% endif %}
    {% if character.StaticMapId == 14 %}Echo: Dark Astoria{% endif %}
    {% if character.StaticMapId == 15 %}'Crey's Folly'{% endif %}
    {% if character.StaticMapId == 16 %}Ouroboros{% endif %}
    {% if character.StaticMapId == 18 %}Abandoned Sewer Network{% endif %}
    {% if character.StaticMapId == 19 %}Echo: Faultline{% endif %}
    {% if character.StaticMapId == 20 %}Terra Volta{% endif %}
    {% if character.StaticMapId == 21 %}'Eden'{% endif %}
    {% if character.StaticMapId == 22 %}'The Hive'{% endif %}
    {% if character.StaticMapId == 23 %}Sewer Network{% endif %}
    {% if character.StaticMapId == 29 %}Galaxy City{% endif %}
    {% if character.StaticMapId == 36 %}Nova Praetoria{% endif %}
    {% if character.StaticMapId == 37 %}Imperial City{% endif %}
    {% if character.StaticMapId == 38 %}Neutropolis{% endif %}
    {% if character.StaticMapId == 39 %}Underground Nova{% endif %}
    {% if character.StaticMapId == 40 %}Precinct Five{% endif %}
    {% if character.StaticMapId == 41 %}Destroyed Galaxy City{% endif %}
    {% if character.StaticMapId == 42 %}Underground Imperial{% endif %}
    {% if character.StaticMapId == 43 %}Dark Astoria{% endif %}
    {% if character.StaticMapId == 44 %}Kallisti Wharf{% endif %}
    {% if character.StaticMapId == 49 %}First Ward{% endif %}
    {% if character.StaticMapId == 51 %}Underground Neutropolis{% endif %}
    {% if character.StaticMapId == 52 %}Night Ward{% endif %}
    {% if character.StaticMapId == 55 %}Fort Trident{% endif %}
    {% if character.StaticMapId == 56 %}The Crucible{% endif %}
    {% if character.StaticMapId == 60 %}Echo: Rikti Crash Site{% endif %}
    {% if character.StaticMapId == 61 %}Peregrine Island{% endif %}
    {% if character.StaticMapId == 62 %}The Hollows{% endif %}
    {% if character.StaticMapId == 63 %}The Tunnels{% endif %}
    {% if character.StaticMapId == 64 %}Firebase Zulu{% endif %}
    {% if character.StaticMapId == 65 %}Cascade Archipelago{% endif %}
    {% if character.StaticMapId == 66 %}The Chantry{% endif %}
    {% if character.StaticMapId == 67 %}The Storm Palace{% endif %}
    {% if character.StaticMapId == 69 %}Striga Isle{% endif %}
    {% if character.StaticMapId == 70 %}Breakout{% endif %}
    {% if character.StaticMapId == 71 %}Mercy Island{% endif %}
    {% if character.StaticMapId == 72 %}Port Oakes{% endif %}
    {% if character.StaticMapId == 73 %}Cap Au Diable{% endif %}
    {% if character.StaticMapId == 74 %}Sharkhead Isle{% endif %}
    {% if character.StaticMapId == 75 %}Nerva Archipelago{% endif %}
    {% if character.StaticMapId == 76 %}St. Martial{% endif %}
    {% if character.StaticMapId == 77 %}Grandville{% endif %}
    {% if character.StaticMapId == 78 %}Bloody Bay{% endif %}
    {% if character.StaticMapId == 79 %}Siren's Call{% endif %}
    {% if character.StaticMapId == 80 %}Warburg{% endif %}
    {% if character.StaticMapId == 81 %}Recluse's Victory{% endif %}
    {% if character.StaticMapId == 82 %}Croatoa{% endif %}
    {% if character.StaticMapId == 83 %}Pocket D{% endif %}
    {% if character.StaticMapId == 84 %}Faultline{% endif %}
    {% if character.StaticMapId == 85 %}Rikti War Zone{% endif %}
    {% if character.StaticMapId == 86 %}'The Abyss'{% endif %}
    {% if character.StaticMapId == 87 %}Monster Island{% endif %}
    {% if character.StaticMapId == 625 %}Echo: Atlas Park{% endif %}
    {% if character.StaticMapId == 626 %}Echo: Galaxy City{% endif %}
    {% if character.StaticMapId == 120 %}(maps/rp/fire){% endif %}
    {% if character.StaticMapId == 121 %}(maps/rp/luau){% endif %}
    {% if character.StaticMapId == 122 %}(maps/rp/harvest){% endif %}
    {% if character.StaticMapId == 123 %}(maps/rp/halloween){% endif %}
    {% if character.StaticMapId == 124 %}(maps/rp/winter){% endif %}
    {% if character.StaticMapId == 10001 %}(maps/_hotaru){% endif %}
    {% if character.StaticMapId == 10002 %}(maps/_mike){% endif %}
    {% if character.StaticMapId == 10003 %}(maps/_naomi){% endif %}
    {% if character.StaticMapId == 10004 %}(maps/_tim){% endif %}
    {% if character.StaticMapId == 10005 %}(maps/_luna){% endif %}
    {% if character.StaticMapId == 10006 %}(maps/_max){% endif %}
    {% if character.StaticMapId == 10007 %}(maps/_obsidian){% endif %}
    {% if character.StaticMapId == 10008 %}(maps/_poison){% endif %}
    {% if character.StaticMapId == 10009 %}(maps/_shadowstar){% endif %}
    {% if character.StaticMapId == 10010 %}(maps/_ascendant){% endif %}

    </li>
{% endfor %}
</ul>