<ul class="character">
{% for character in characters %}
    <li>

    {#### Alignment ####}

    {% set PlayerType, PlayerSubType, PlayerPraetorian = 0, 0, 0 %}

    {% if character.PlayerType is defined                        %}
    {%    set PlayerType = character.PlayerType                  %}
    {% endif                                                     %}

    {% if character.PlayerSubType is defined                     %}
    {%    set PlayerSubType = character.PlayerSubType            %}
    {% endif                                                     %}

    {% if character.PraetorianProgress is defined                %}
    {%    set PlayerPraetorian = character.PraetorianProgress    %}
    {% endif                                                     %}

    {% if PlayerPraetorian == 1                                  %}
        <img src="{{portal_url}}images/icons/alignment/neutral.png" alt="Neutral">
    {% elseif PlayerPraetorian == 2                              %}
        {% if PlayerType == 0  %}
            <img src="{{portal_url}}images/icons/alignment/resistance.png" alt="Praetorian Resistance">
        {% endif %}

        {% if PlayerType == 1 %}
            <img src="{{portal_url}}images/icons/alignment/loyalist.png" alt="Praetorian Loyalist">
        {% endif %}
    {% elseif PlayerPraetorian == 6                              %}
        <img src="{{portal_url}}images/icons/alignment/neutral.png" alt="Neutral">
    {% else                                                      %}
        {% if PlayerType == 0 and PlayerSubType == 0 %}
            <img src="{{portal_url}}images/icons/alignment/hero.png" alt="Hero">
        {% endif %}

        {% if PlayerType == 0 and PlayerSubType == 1 %}
            <img src="{{portal_url}}images/icons/alignment/hero.png" alt="Paragon">
        {% endif %}

        {% if PlayerType == 0 and PlayerSubType == 2 %}
            <img src="{{portal_url}}images/icons/alignment/vigilante.png" alt="Vigilante">
        {% endif %}

        {% if PlayerType == 1 and PlayerSubType == 0 %}
            <img src="{{portal_url}}images/icons/alignment/villain.png" alt="Villain">
        {% endif %}

        {% if PlayerType == 1 and PlayerSubType == 1 %}
            <img src="{{portal_url}}images/icons/alignment/villain.png" alt="Tyrant">
        {% endif %}

        {% if PlayerType == 1 and PlayerSubType == 2 %}
            <img src="{{portal_url}}images/icons/alignment/rogue.png" alt="Rogue">
        {% endif %}
    {% endif                                                     %}

    {#### Class #####}

    {% if character.Class == 1 %}<img src="{{portal_url}}images/icons/archetype/blaster.png" alt="Blaster">{% endif %}
    {% if character.Class == 2 %}<img src="{{portal_url}}images/icons/archetype/controler.png" alt="Controller">{% endif %}
    {% if character.Class == 3 %}<img src="{{portal_url}}images/icons/archetype/defender.png" alt="Defender">{% endif %}
    {% if character.Class == 4 %}<img src="{{portal_url}}images/icons/archetype/scrapper.png" alt="Scrapper">{% endif %}
    {% if character.Class == 5 %}<img src="{{portal_url}}images/icons/archetype/tanker.png" alt="Tanker">{% endif %}
    {% if character.Class == 9198 %}<img src="{{portal_url}}images/icons/archetype/mastermind.png" alt="Mastermind">{% endif %}
    {% if character.Class == 9200 %}<img src="{{portal_url}}images/icons/archetype/stalker.png" alt="Stalker">{% endif %}
    {% if character.Class == 9201 %}<img src="{{portal_url}}images/icons/archetype/brute.png" alt="Brute">{% endif %}
    {% if character.Class == 9700 %}<img src="{{portal_url}}images/icons/archetype/dominator.png" alt="Dominator">{% endif %}
    {% if character.Class == 10929 %}<img src="{{portal_url}}images/icons/archetype/corruptor.png" alt="Corruptor">{% endif %}
    {% if character.Class == 7076 %}<img src="{{portal_url}}images/icons/archetype/warshade.png" alt="Warshade">{% endif %}
    {% if character.Class == 7018 %}<img src="{{portal_url}}images/icons/archetype/peacebringer.png" alt="Peacebringer">{% endif %}
    {% if character.Class == 37071 %}<img src="{{portal_url}}images/icons/archetype/arachnos_soldier.png" alt="Arachnos Soldier">{% endif %}
    {% if character.Class == 37072 %}<img src="{{portal_url}}images/icons/archetype/arachnos_widow.png" alt="Arachnos Widow">{% endif %}

    {#### Origin #####}

    {% if character.Origin == 6 %}<img src="{{portal_url}}images/icons/origin/science.png" alt="Science">{% endif %}
    {% if character.Origin == 7 %}<img src="{{portal_url}}images/icons/origin/mutation.png" alt="Mutation">{% endif %}
    {% if character.Origin == 8 %}<img src="{{portal_url}}images/icons/origin/magic.png" alt="Magic">{% endif %}
    {% if character.Origin == 9 %}<img src="{{portal_url}}images/icons/origin/technology.png" alt="Technology">{% endif %}
    {% if character.Origin == 10 %}<img src="{{portal_url}}images/icons/origin/natural.png" alt="Natural">{% endif %}

    <a href="./api/character/raw?q={{character.datauri}}">{{character.Name}}</a>
    </li>
{% endfor %}
</ul>