{% extends "template-base.phtml" %}

{% block title %}Account Portal{% endblock %}

{% block content %}
<div class="block">
    <div class="blocktitle">
        Welcome {{username}}
    </div>
    <div class="blockbody">
        If you would like to change your password, enter a new password below, then click "Change Password".
        <form method="post" action="changepassword">
            <table width="100%">
                <tr>
                    <td align="right"><label for="new_password">New Password</label></td>
                    <td><input type="password" name="new_password" maxlength=16></td>
                </tr><tr>
                <tr>
                    <td colspan="2" align="right">
                        <input type="submit" name="change" value="Change Password">
                    </td>
                </tr>
            </table>
            <input type="hidden" name="{{csrf.keys.name}}" value="{{csrf.name}}">
            <input type="hidden" name="{{csrf.keys.value}}" value="{{csrf.value}}">
        </form>
    </div>
</div>

<div class="block">
    <div class="blocktitle">
        Your Characters
    </div>
    <div class="blockbody">
        <ul>
            {% for character in characters %}
                <li>{{character.Name}}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}