{% extends "template-base.phtml" %}

{% block title %}Account Portal{% endblock %}

{% block content %}
<div class="block">
    <div class="blocktitle">
        Welcome {{username}}
    </div>
    <div class="blockbody">
        If you would like to change your password, enter a new password below, then click "Change Password".
        <form method="post" action="changepassword">
            <table width="100%">
                <tr>
                    <td align="right"><label for="password">New Password</label></td>
                    <td><input type="password" name="password" maxlength=16></td>
                </tr><tr>
                <tr>
                    <td colspan="2" align="right">
                        <input type="submit" name="change" value="Change Password">
                    </td>
                </tr>
            </table>
            <input type="hidden" name="{{csrf.keys.name}}" value="{{csrf.name}}">
            <input type="hidden" name="{{csrf.keys.value}}" value="{{csrf.value}}">
        </form>
    </div>
</div>

<div class="block">
    <div class="blocktitle">
        Your Characters
    </div>
    <div class="blockbody">
        <ul>
            {% for character in characters %}
                <li><a href="./api/character/{{character.datauri}}/raw">{{character.Name}}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="block">
    <div class="blocktitle">
        Character Transfer
    </div>
    <div class="blockbody">
        <form method="post" action="./federation/transfer-character-request">
            <p>Please select a server and character to transfer:</p>
            <label for="server">Server</label>
            <select name="server">
                {% for server in federation %}
                    <option value="{{server.Name}}">{{server.Name}}</option>
                {% endfor %}
            </select>
            <br />
            <label for="character">Character</label>
            <select name="character">
            {% for character in characters %}
                <option value="{{character.datauri}}">{{character.Name}}</option>
            {% endfor %}
            </select>
            <br />
            <input type="submit" name="select" value="Transfer Now"/>
            <input type="hidden" name="{{csrf.keys.name}}" value="{{csrf.name}}">
            <input type="hidden" name="{{csrf.keys.value}}" value="{{csrf.value}}">
        </form>
    </div>
</div>
{% endblock %}